### ISSUE TITLE
how to remove with trial key

### ISSUE THREAD

**Issue by neverrop** [northword/zotero-android-nightly-build#2]
Thanks for great job!!
I got water marks on top of each pdf, any one have idea how to remove them with trial key, thanks

**Comment by northword** [comment]
This repo is for development and testing only, not for production. For daily use, please download the official release from the Play Store. The official build includes the key and does not show the watermark.

You can also [buy the key yourself](https://pspdfkit.com/pricing/) and compile the APK yourself according to [the variables in the CI](https://github.com/northword/zotero-android-nightly-build/blob/c3e2e71bb26c18110d2cdb1d2028340e072282b6/.github/workflows/ci.yml#L71).

**Comment by neverrop** [comment]
> This repo is for development and testing only, not for production. For daily use, please download the official release from the Play Store. The official build includes the key and does not show the watermark.
> 
> You can also [buy the key yourself](https://pspdfkit.com/pricing/) and compile the APK yourself according to [the variables in the CI](https://github.com/northword/zotero-android-nightly-build/blob/c3e2e71bb26c18110d2cdb1d2028340e072282b6/.github/workflows/ci.yml#L71).

got it. thank you!

**Comment by zrgtzjwh** [comment]
Have anyone buy a key, and remove the watermark? how much this pdfkit?
