### ISSUE TITLE
an available version for Huawei matebook android 

### ISSUE THREAD

**Issue by zrgtzjwh** [northword/zotero-android-nightly-build#3]
I found a version of Zotero for Android that can run on the Huawei HarmonyOS is this  [URL](https://ftp.linxingzhong.top/Zotero_android/). However, when I use this repository to recompile the software, it doesn't run (it can be installed, but cannot be opened). Have anyone know some information about this url? 
I want use pspdfkit trial key recompile this project.

**Comment by northword** [comment]
The APK file included in the link you gave is also compiled from this repository.

I'm not sure what kind of changes you've made and I don't have a HarmonyOS device to test it on to give any more advice.

Also, the HarmonyOS may not be (or full) compatible with Android.
